vanilla:
  server:
    port: 8080
    backlog: 50
    host: localhost
    filesystem:
      maxInMemory: 30KB
      basedir: "./src/test/resources/sampledirectory"
    http:
      keepAliveTimeout: 10s

logging:
  level:
    root: INFO