vanilla:
  server:
    port: 8080
    backlog: 50
    host: localhost
    filesystem:
      maxInMemory: 50MB
      basedir: "./src/test/resources/sampledirectory"
    http:
      keepAliveTimeout: 10s
      chunkedEncodingBufferSize: 10KB

logging:
  level:
    root: INFO