vanilla:
  server:
    port: 8080
    backlog: 50
    host: localhost
    basedir: "./src/test/resources/sampledirectory"
    http:
      requestBufferSizeInByte: 8096

logging:
  level:
    root: INFO