name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'bug/*'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Get Maven Version
        run: mvn --version
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
